[mypy]
python_version = 3.12
strict = True
files = shared/beachhub_shared, core/beachhub_core/services, core/beachhub_core/zahlung
plugins = pydantic.mypy
[mypy-nacl.*,weasyprint.*,apscheduler.*,pyotp.*,aiosmtplib.*]
ignore_missing_imports = True
