"""stammdaten und system

Revision ID: 0001
Revises:
Create Date: 2026-09-08 23:07:18.062994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("passwort_hash", sa.String(length=300), nullable=False),
        sa.Column("totp_secret", sa.String(length=64), nullable=False),
        sa.Column("rolle", sa.String(length=10), nullable=False),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit",
        sa.Column("zeitpunkt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=True),
        sa.Column("quelle", sa.String(length=10), nullable=False),
        sa.Column("objekt_typ", sa.String(length=40), nullable=False),
        sa.Column("objekt_id", sa.UUID(), nullable=True),
        sa.Column("vorher_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nachher_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ausnahmetag",
        sa.Column("datum", sa.Date(), nullable=False),
        sa.Column("geschlossen", sa.Boolean(), nullable=False),
        sa.Column("oeffnet", sa.Time(), nullable=True),
        sa.Column("schliesst", sa.Time(), nullable=True),
        sa.Column("grund", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("datum"),
    )
    op.create_table(
        "betriebszeit",
        sa.Column("wochentag", sa.Integer(), nullable=False),
        sa.Column("oeffnet", sa.Time(), nullable=False),
        sa.Column("schliesst", sa.Time(), nullable=False),
        sa.Column("gueltig_von", sa.Date(), nullable=True),
        sa.Column("gueltig_bis", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feld",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.Column("reihenfolge", sa.Integer(), nullable=False),
        sa.Column("ha_licht_entity", sa.String(length=200), nullable=True),
        sa.Column("ha_praesenz_entity", sa.String(length=200), nullable=True),
        sa.Column("heizzone", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "konfiguration",
        sa.Column("schluessel", sa.String(length=60), nullable=False),
        sa.Column("wert", sa.String(length=500), nullable=False),
        sa.Column("typ", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("schluessel"),
    )
    op.create_table(
        "kundengruppe",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("standard_zahlungsart", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "lesestand_version",
        sa.Column("dokument", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("signiert_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("geaendert", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("dokument"),
    )
    op.create_table(
        "feld_raster",
        sa.Column("feld_id", sa.UUID(), nullable=False),
        sa.Column("wochentag", sa.Integer(), nullable=True),
        sa.Column("modus", sa.String(length=10), nullable=False),
        sa.Column("slot_minuten", sa.Integer(), nullable=True),
        sa.Column("fenster_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feld_id"],
            ["feld.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tarif",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("preis", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("feld_id", sa.UUID(), nullable=True),
        sa.Column("wochentag", sa.Integer(), nullable=True),
        sa.Column("uhrzeit_von", sa.Time(), nullable=True),
        sa.Column("uhrzeit_bis", sa.Time(), nullable=True),
        sa.Column("kundengruppe_id", sa.UUID(), nullable=True),
        sa.Column("gueltig_von", sa.Date(), nullable=True),
        sa.Column("gueltig_bis", sa.Date(), nullable=True),
        sa.Column("aktiv", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feld_id"],
            ["feld.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kundengruppe_id"],
            ["kundengruppe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tarif")
    op.drop_table("feld_raster")
    op.drop_table("lesestand_version")
    op.drop_table("kundengruppe")
    op.drop_table("konfiguration")
    op.drop_table("feld")
    op.drop_table("betriebszeit")
    op.drop_table("ausnahmetag")
    op.drop_table("audit")
    op.drop_table("app_setting")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
