"""kunden

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-08 23:23:54.584857

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kunde",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("adresse_strasse", sa.String(length=200), nullable=False),
        sa.Column("adresse_plz", sa.String(length=10), nullable=False),
        sa.Column("adresse_ort", sa.String(length=100), nullable=False),
        sa.Column("kundengruppe_id", sa.UUID(), nullable=False),
        sa.Column("zahlungsart", sa.String(length=10), nullable=False),
        sa.Column("guthaben", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("portal_konto_id", sa.UUID(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=100), nullable=True),
        sa.Column("anonymisiert_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kundengruppe_id"],
            ["kundengruppe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("portal_konto_id"),
        sa.CheckConstraint("guthaben >= 0", name="kunde_guthaben_nicht_negativ"),
    )
    op.create_table(
        "guthaben_buchung",
        sa.Column("kunde_id", sa.UUID(), nullable=False),
        sa.Column("betrag", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("art", sa.String(length=20), nullable=False),
        sa.Column("bezug_id", sa.UUID(), nullable=True),
        sa.Column("notiz", sa.String(length=500), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kunde_id"],
            ["kunde.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guthaben_buchung")
    op.drop_table("kunde")
    # ### end Alembic commands ###
