"""buchungen

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-08 23:35:58.397509

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sperre",
        sa.Column("feld_id", sa.UUID(), nullable=True),
        sa.Column("beginn", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ende", sa.DateTime(timezone=True), nullable=False),
        sa.Column("grund", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("feld_id"), "="),
            (sa.text("tstzrange(beginn, ende)"), "&&"),
            where=sa.text("feld_id IS NOT NULL"),
            using="gist",
            name="sperre_keine_ueberlappung",
        ),
        sa.ForeignKeyConstraint(
            ["feld_id"],
            ["feld.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dauerbuchung",
        sa.Column("kunde_id", sa.UUID(), nullable=False),
        sa.Column("feld_id", sa.UUID(), nullable=False),
        sa.Column("wochentag", sa.Integer(), nullable=False),
        sa.Column("start", sa.Time(), nullable=False),
        sa.Column("ende", sa.Time(), nullable=False),
        sa.Column("gueltig_von", sa.Date(), nullable=False),
        sa.Column("gueltig_bis", sa.Date(), nullable=False),
        sa.Column("pin_hash", sa.String(length=200), nullable=False),
        sa.Column("pin_verschluesselt", sa.String(length=300), nullable=False),
        sa.Column("beendet_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("beendet_ab", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feld_id"],
            ["feld.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kunde_id"],
            ["kunde.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buchung",
        sa.Column("feld_id", sa.UUID(), nullable=False),
        sa.Column("kunde_id", sa.UUID(), nullable=False),
        sa.Column("beginn", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ende", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("preis", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("zahlungsart", sa.String(length=10), nullable=False),
        sa.Column("pin_hash", sa.String(length=200), nullable=True),
        sa.Column("pin_verschluesselt", sa.String(length=300), nullable=True),
        sa.Column("dauerbuchung_id", sa.UUID(), nullable=True),
        sa.Column("anfrage_id", sa.UUID(), nullable=True),
        sa.Column("reserviert_bis", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anwesenheit", sa.String(length=20), nullable=False),
        sa.Column("quelle", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("feld_id"), "="),
            (sa.text("tstzrange(beginn, ende)"), "&&"),
            where=sa.text(
                "status IN ('angefragt','reserviert','bestaetigt','durchgefuehrt','nicht_erschienen')"  # noqa: E501
            ),
            using="gist",
            name="buchung_keine_ueberlappung",
        ),
        sa.ForeignKeyConstraint(
            ["dauerbuchung_id"],
            ["dauerbuchung.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feld_id"],
            ["feld.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kunde_id"],
            ["kunde.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anfrage_id"),
    )
    op.create_table(
        "storno",
        sa.Column("buchung_id", sa.UUID(), nullable=False),
        sa.Column("zeitpunkt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("durch", sa.String(length=10), nullable=False),
        sa.Column("kostenfrei", sa.Boolean(), nullable=False),
        sa.Column("grund", sa.String(length=300), nullable=False),
        sa.Column("nachbuchung_offen", sa.Boolean(), nullable=False),
        sa.Column("nachbuchung_buchung_id", sa.UUID(), nullable=True),
        sa.Column("freigestellt_betrag", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buchung_id"],
            ["buchung.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nachbuchung_buchung_id"],
            ["buchung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("buchung_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storno")
    op.drop_table("buchung")
    op.drop_table("dauerbuchung")
    op.drop_table("sperre")
    # ### end Alembic commands ###
