"""rechnungen

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-09 00:58:44.872501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nummernkreis",
        sa.Column("jahr", sa.Integer(), nullable=False),
        sa.Column("letzte_nummer", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("jahr"),
    )
    op.create_table(
        "rechnung",
        sa.Column("nummer", sa.String(length=12), nullable=False),
        sa.Column("kunde_id", sa.UUID(), nullable=False),
        sa.Column("art", sa.String(length=10), nullable=False),
        sa.Column("datum", sa.Date(), nullable=False),
        sa.Column("leistung_von", sa.Date(), nullable=False),
        sa.Column("leistung_bis", sa.Date(), nullable=False),
        sa.Column("faellig_am", sa.Date(), nullable=False),
        sa.Column("ust_satz", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("netto", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("ust", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("brutto", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("bezahlt_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_pfad", sa.String(length=300), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column("storniert_durch_id", sa.UUID(), nullable=True),
        sa.Column("adresse_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["kunde_id"], ["kunde.id"]),
        sa.ForeignKeyConstraint(["storniert_durch_id"], ["rechnung.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nummer"),
    )
    op.create_table(
        "rechnung_position",
        sa.Column("rechnung_id", sa.UUID(), nullable=False),
        sa.Column("reihenfolge", sa.Integer(), nullable=False),
        sa.Column("buchung_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("menge", sa.Integer(), nullable=False),
        sa.Column("einzelpreis_brutto", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("ust_satz", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("brutto", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["buchung_id"], ["buchung.id"]),
        sa.ForeignKeyConstraint(["rechnung_id"], ["rechnung.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_rechnung_position_buchung",
        "rechnung_position",
        ["buchung_id"],
        unique=True,
        postgresql_where=sa.text("buchung_id IS NOT NULL"),
    )
    op.add_column("buchung", sa.Column("rechnung_position_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_buchung_rechnung_position_id",
        "buchung",
        "rechnung_position",
        ["rechnung_position_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_buchung_rechnung_position_id", "buchung", type_="foreignkey")
    op.drop_column("buchung", "rechnung_position_id")
    op.drop_index("ux_rechnung_position_buchung", table_name="rechnung_position")
    op.drop_table("rechnung_position")
    op.drop_table("rechnung")
    op.drop_table("nummernkreis")
    # ### end Alembic commands ###
